<?php

/**
 * Implementation of hook_rules_event_info().
 */
/*function rule_rules_event_info() {
  $items = array(
    'newsletter_register_email' => array(
      'label' => t('An event to trigger when an user is subscribed to newsletters.'),
      'group' => t('User'),
      'variables' => array(
        'account' => array(
          'type' => 'user',
          'label' => t('updated user'),
        ),
      ),
    ),
  );
  return $items;
}*/

/**
 * Implements hook_node_insert().
 */
/*function rule_node_insert($node) {
 //gloal $node;
  if ($node->type == 'Review') {
    drupal_set_message('Yes');
  }
}*/


/*
* Implements hook_node_presave()
*
* Act on a node being inserted.
*
*presave
* @param $node
* The node that is being inserted.
*/

function rule_node_presave($node)
{
  global $user;

  if ($node->type == 'review' && $node->is_new) {
    // drupal_set_message("Thanks for creating a Review, your node id is " . $node->nid);
    $num = og_get_groups_by_user();
    $number_group = $node->field_company['und'][0]['target_id'];
    //drupal_set_message('<pre>'.print_r($num, true).'<pre>');
    //drupal_set_message('<pre>'.print_r($number_group, true).'<pre>');
    //drupal_set_message('<pre>'.print_r($node, true).'<pre>');


    $ismember = false;
    foreach ($num['node'] as $key => $value) {
      if ($value == $number_group) {
        $ismember = true;
      }
    }
    if ($ismember) {
      $node->status = 0;
      drupal_set_message(t("Sorry, but you can't add your company for review."), 'error');
    } else {
      $node->status = 1;
      //$form_state['redirect'] = "node/$number_group";
      drupal_set_message(t("Thank you for your feedback!"), 'status');
      $array = array(
        'context' => array(
          'subject' => 'Some subject',
          'message' => 'Some message',
        )
        );
      if (drupal_mail('system', 'mail', $user->mail, language_default(), $array)){
        drupal_set_message("ok");
        else {
          drupal_set_message("no");
        }
      }
      }
      drupal_goto("node/$number_group");
    }
    //drupal_set_message("user: ".$user->uid);

  }
}
