<?php

function rule_node_presave($node)
{
  global $user;

  if ($node->type == 'review' && $node->is_new) {
    // drupal_set_message("Thanks for creating a Review, your node id is " . $node->nid);
    $num = og_get_groups_by_user();
    $number_group = $node->field_company['und'][0]['target_id'];
    //drupal_set_message('<pre>'.print_r($num, true).'<pre>');
    //drupal_set_message('<pre>'.print_r($number_group, true).'<pre>');
    //drupal_set_message('<pre>'.print_r($node, true).'<pre>');


    $ismember = false;
    foreach ($num['node'] as $key => $value) {
      if ($value == $number_group) {
        $ismember = true;
      }
    }
    if ($ismember) {
      $node->status = 0;
      drupal_set_message(t("Sorry, but you can't add your company for review."), 'error');
    } else {
      $node->status = 1;
      //$form_state['redirect'] = "node/$number_group";
      //drupal_set_message(t("Thank you for your feedback!"), 'status');
      $array = array(
        'context' => array(
          'subject' => 'Add review',
          'message' => 'l(node/$number_group)',
        )
        );
      if (drupal_mail('system', 'mail', $user->mail, language_default(), $array)){
        drupal_set_message(t("Thank you for your feedback!"), 'status');}
        else {
          drupal_set_message("error");
        }
      //drupal_goto("node/$number_group");
      }      
       
    }    
}
   